#!/bin/bash


echo "//this file is auto-generated by generate_exports.sh " > ./src/main.ts

find ./src/components -name '*.tsx' | while read line; do
  filename=${line%.tsx}
  relativepath=$(sed 's/.*components\/\(.*\).tsx.*/\1/' <<< "$line")
  echo "export { ${filename##*/} } from './components/${relativepath}';" >> ./src/main.ts
done
