#!/bin/bash

green=`tput setaf 2`
reset=`tput sgr0`

echo "// this file is auto-generated by ./scripts/generate_exports.sh" > ./src/main.ts

find ./src/components -name '*.tsx' | while read line; do
  filename=${line%.tsx}
  relativepath=$(sed 's/.*components\/\(.*\).tsx.*/\1/' <<< "$line")
  echo "export { ${filename##*/} } from './components/${relativepath}';" >> ./src/main.ts
done


echo "${green} ************* Generated ./src/main.ts ************* ${reset}"
